spring:
  application:
    name: smg
  datasource:
    url: jdbc:postgresql://localhost:5432/smg
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: prinslaeileen@gmail.com
    password: fwnh vhnj ktmo ipmf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
